NODES = {
    "master01" => {
        "box" => "generic/ubuntu2204",
        "cpus" => 1,
        "memory" => 2048,
        "ip" => "10.100.0.11",
    },
    "node01" => {
        "box" => "generic/ubuntu2204",
        "cpus" => 1,
        "memory" => 2048,
        "ip" => "10.100.0.21",
    },
    "node02" => {
        "box" => "generic/ubuntu2204",
        "cpus" => 1,
        "memory" => 2048,
        "ip" => "10.100.0.22",
    }
}

Vagrant.configure("2") do |config|
    NODES.each do |(name, params)|
        config.vm.define "#{name}" do |c|
            c.vm.box = "#{params['box']}"
            c.vm.hostname = "#{name}"
            c.vm.network "public_network", libvirt__network_name: "k8s-network", ip: "#{params['ip']}", libvirt__netmask: "255.255.255.0", dev: "k8s", mode: "bridge", type: "bridge"
            c.vm.provider "libvirt" do |lv|
                lv.memory = params['memory']
                lv.cpus = params['cpus']
            end
            c.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/key.pub"
            c.vm.provision "shell", inline: <<-SHELL
            sudo cat /home/vagrant/key.pub >> /home/vagrant/.ssh/authorized_keys
            SHELL
        end
    end
end