---
apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    [
      {
        "clusterID": "c84eb914-de3d-11ee-9580-453a9a3918ad",
        "monitors": [
          "10.100.2.11:6789",
          "10.100.2.12:6789",
          "10.100.2.13:6789"
        ]
      }
    ]
metadata:
  name: ceph-csi-config

---
apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    {}
metadata:
  name: ceph-csi-encryption-kms-config

---
apiVersion: v1
kind: ConfigMap
data:
  ceph.conf: |
    [global]
    auth_cluster_required = cephx
    auth_service_required = cephx
    auth_client_required = cephx
  # keyring is a required key and its value should be empty
  keyring: |
metadata:
  name: ceph-config

---
apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: default
stringData:
  userID: kubernetes
  userKey: AQD5texlBajUNRAA2YoLRmakjaRjshEJkqVbNA==