kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
    disableDefaultCNI: true
    podSubnet: 192.168.0.0/16 # For default Calico subnet
nodes:
    - role: control-plane
      image: kindest/node:v1.29.2@sha256:acc9e82a5a5bd3dfccfd03117e9ef5f96b46108b55cd647fb5e7d0d1a35c9c6f
    - role: worker
